### PR TITLE
Rebar does not support $MAKE (to my knowledge), so use a shim makefile

### PR DESCRIPTION
**Pull request by Vagabond**
GNU make will look for GNUmakefile before Makefile, so move the makefile
over there and add a stub Makefile that simply defines the target that
rebar tries to build. This fixes the case where make is not gnu make.

cc @jaredmorrow

### CODE REVIEW

**Comment by slfritchie** [comment]
Andrew, do you know if this plays nicely with rebar when faulterl is a dependency?

**Comment by Vagabond** [comment]
Yes, that is how I developed it. I tested with faulterl as a dep and with it as the toplevel project on FreeBSD and it worked. I didn't actually test on linux or OSX.

**Comment by slfritchie** [comment]
OK, thanks.  I'll finish taking a look at this tomorrow.  Bitcask is the only Basho repo that's using it.

BTW, it's quite likely that I'll switch away from the code generator currently here and switch to something more like this: https://github.com/slfritchie/lfi/compare/slf-trigger-parity-attempt1 ... Con: XML.  Pro: someone else's code that works better in almost all ways, now that Paul has fixed some OS X + compiler problems that was keeping me from using lfi in the first place.

**Comment by slfritchie** [comment]
Thanks, Andrew!

**Pull request merged**
